### ISSUE TITLE
Have a platform mapper to support the different tool mappings

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-nornir#58]
### Environment
* Python version:  3.7+
* Nautobot version:  1.3+
* nautobot-plugin-nornir version: 1.0.0

### Proposed Functionality
Utilize netutils mapping functions or user defined mappings to tranform the inventory platform for different nornir task plugins.  

### Use Case
Platform definitions between nautobot, netmiko, scrapli, etc aren't a one to one mapping.  If you using nautobot inventory but want to call netmiko or another nornir task, you currently have to go manually update the platform entry in the nornir inventory host object.

Having a easy way to transpose this would be helpful and avoid having different platform mapping functions spread out between different plugins.

**Comment by alextremblay** [comment]
I believe this has been addressed in nautobot v1.6?

**Comment by Kircheneer** [comment]
I think so, too: https://docs.nautobot.com/projects/plugin-nornir/en/latest/admin/migrating_to_v2/#platform-network-driver

**Comment by jeffkala** [comment]
this is done in core.
